import os
import sys
import argparse
import re
import shutil
from pathlib import Path
from datetime import datetime
from config_utils import get_core_path, get_target_path, is_mirror_mode

EXCLUDED_FILES = {"index.md", "project_tree.md"}

TYPE_ORDER = ["folder", "entry-point", "governance", "state", "log", "volatile", "template", "index", "other"]
TYPE_LABELS = {
    "folder": "Folders",
    "entry-point": "Entry Points",
    "governance": "Governance",
    "state": "State",
    "log": "Logs",
    "volatile": "Volatile",
    "template": "Templates",
    "index": "Indexes",
    "other": "Other"
}

def has_frontmatter(file_path: Path) -> bool:
    try:
        with open(file_path, 'r', encoding='utf-8-sig') as f:
            first_line = f.readline().strip()
            return first_line == "---"
    except Exception:
        return False

def get_frontmatter_field(file_path: Path, field: str) -> str:
    try:
        with open(file_path, 'r', encoding='utf-8-sig') as f:
            in_frontmatter = False
            for line in f:
                stripped = line.strip()
                if stripped == "---":
                    if not in_frontmatter:
                        in_frontmatter = True
                        continue
                    else:
                        break
                
                if in_frontmatter:
                    match = re.match(rf"^{field}:\s*[\"']?(.+?)[\"']?\s*$", stripped)
                    if match:
                        return match.group(1)
    except Exception:
        pass
    return ""

def add_frontmatter_if_missing(folder_path: Path, today_str: str):
    try:
        md_files = [f for f in folder_path.iterdir() if f.is_file() and f.suffix == ".md" and f.name not in EXCLUDED_FILES]
    except Exception:
        return

    for file_path in md_files:
        if not has_frontmatter(file_path):
            base_name = file_path.stem
            frontmatter = f"---\ntitle: \"{base_name}\"\ndescription: \"\"\ntype: \"\"\nupdated: \"{today_str}\"\n---\n\n"
            try:
                content = file_path.read_text(encoding='utf-8-sig')
                file_path.write_text(frontmatter + content, encoding='utf-8')
                print(f"  [frontmatter added] {file_path.name}")
            except Exception as e:
                print(f"  [Error] Could not process {file_path.name}: {e}")

def generate_index(folder_path: Path, today_str: str, output_folder: Path, is_mirror: bool):
    try:
        md_files = sorted([f for f in folder_path.iterdir() if f.is_file() and f.suffix == ".md" and f.name not in EXCLUDED_FILES], key=lambda x: x.name)
        directories = sorted([d for d in folder_path.iterdir() if d.is_dir() and not d.name.startswith('.')], key=lambda x: x.name)
    except Exception:
        return

    if not md_files and not directories:
        return

    groups = {}

    if directories:
        groups["folder"] = []
        for d in directories:
            if is_mirror:
                link = f"[{d.name}]({d.name}/index.md)"
            else:
                link = f"[[{d.name}]]"
                
            groups["folder"].append({
                "Link": link,
                "Description": "Directory",
            })

    for f in md_files:
        f_type = get_frontmatter_field(f, "type")
        if not f_type.strip():
            f_type = "other"
            
        if f_type not in groups:
            groups[f_type] = []
            
        desc = get_frontmatter_field(f, "description")
        
        if is_mirror:
            link_path = f"file:///{f.resolve().as_posix()}"
            link = f"[{f.name}]({link_path})"
        else:
            link = f"[[{f.stem}]]"
        
        groups[f_type].append({
            "Link": link,
            "Description": desc,
        })

    folder_name = folder_path.name

    output = []
    output.append("---")
    output.append(f'title: "Index - {folder_name}"')
    output.append(f'description: "Auto-generated index for {folder_name}. Do not edit manually."')
    output.append('type: "index"')
    output.append(f'updated: "{today_str}"')
    output.append("---")
    output.append("")
    output.append(f"# Index - {folder_name}")
    output.append("")
    output.append("> Auto-generated by `generate_index.py`. Do not edit manually.")
    if is_mirror:
        output.append("> **GHOST MIRROR:** Links point to the external project.")
    output.append("> Regenerate after adding, moving or deleting files.")
    output.append("")

    sorted_types = [t for t in TYPE_ORDER if t in groups]
    remaining_types = sorted([t for t in groups.keys() if t not in TYPE_ORDER])
    all_types = sorted_types + remaining_types

    for t in all_types:
        label = TYPE_LABELS.get(t, t)
        output.append(f"## {label}")
        output.append("")
        output.append("| File | Description |")
        output.append("| :--- | :--- |")
        for entry in groups[t]:
            desc = entry["Description"] if entry["Description"] else "-"
            output.append(f"| {entry['Link']} | {desc} |")
        output.append("")

    output_folder.mkdir(parents=True, exist_ok=True)
    index_path = output_folder / "index.md"
    try:
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(output) + "\n")
        print(f"  [index generated] {index_path}")
    except Exception as e:
        print(f"  [Error] Could not write {index_path}: {e}")

def main():
    parser = argparse.ArgumentParser(description="Index generator for AutoIgnite · Plug & Work AI Context Kit")
    parser.add_argument("path", nargs="?", default=None, help="Folder path to process (Optional, ignores ini if provided)")
    parser.add_argument("--recursive", "-r", action="store_true", help="Process subfolders recursively")
    
    args = parser.parse_args()
    
    target_path = Path(args.path) if args.path else get_target_path()
    resolved_path = target_path.resolve()
    
    if not resolved_path.exists():
        print(f"ERROR: The path '{resolved_path}' does not exist.", file=sys.stderr)
        sys.exit(1)

    mirror_mode = is_mirror_mode() if not args.path else False
    core_path = get_core_path()
    
    print()
    print("=== generate_index.py ===")
    print(f"Target Path: {resolved_path}")
    if mirror_mode:
        print(f"Mode: OBSERVER (Ghost Mirror in {core_path}/targets_mirror/)")
    else:
        print("Mode: NATIVE (In-Place OKF)")
    print()

    today_str = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    # If mirror mode, pre-clean the mirror directory if regenerating everything
    mirror_root = None
    if mirror_mode:
        target_name = resolved_path.name
        mirror_root = (core_path / "targets_mirror" / target_name).resolve()
        # If recursive, total rebuild is assumed
        if args.recursive and mirror_root.exists():
            print(f"Cleaning previous mirror at {mirror_root}...")
            shutil.rmtree(mirror_root)
        mirror_root.mkdir(parents=True, exist_ok=True)

    folders_to_process = [resolved_path]
    
    if args.recursive:
        for root, dirs, files in os.walk(resolved_path):
            dirs[:] = [d for d in dirs if not d.startswith('.')]
            if Path(root) != resolved_path:
                folders_to_process.append(Path(root))

    for folder in folders_to_process:
        print(f"Processing: {folder}")
        
        # Determine output directory
        if mirror_mode:
            rel_path = folder.relative_to(resolved_path)
            output_folder = mirror_root / rel_path
        else:
            output_folder = folder
            
        if not mirror_mode:
            print("  STEP 1 - Frontmatter")
            add_frontmatter_if_missing(folder, today_str)
            
        print("  STEP 2 - Index")
        generate_index(folder, today_str, output_folder, mirror_mode)

    print("\nReady.\n")

if __name__ == "__main__":
    main()
