import os
import sys
from datetime import datetime
from pathlib import Path
from config_utils import get_core_path, get_target_path, is_mirror_mode

# Configuration
EXCLUDED_FOLDERS = {".git", ".obsidian", ".trash", "node_modules", "__pycache__"}

# Unicode characters for the tree
BRANCH = "├── "
LAST = "└── "
PIPE = "│   "
SPACE = "    "

def generate_tree(dir_path: Path, prefix: str = "", lines=None):
    if lines is None:
        lines = []

    try:
        items = list(dir_path.iterdir())
        items = [i for i in items if i.name not in EXCLUDED_FOLDERS]
        
        # Sort: folders first, then files, and alphabetically
        items.sort(key=lambda x: (not x.is_dir(), x.name.lower()))
        
        count = len(items)
        for i, item in enumerate(items):
            is_last = (i == count - 1)
            connector = LAST if is_last else BRANCH
            
            lines.append(f"{prefix}{connector}{item.name}")
            
            if item.is_dir():
                new_prefix = prefix + (SPACE if is_last else PIPE)
                generate_tree(item, new_prefix, lines)
                
    except PermissionError:
        pass
        
    return lines

def main():
    target_path = Path(sys.argv[1]) if len(sys.argv) > 1 else get_target_path()
    
    if not target_path.exists():
        print(f"ERROR: The path '{target_path}' does not exist.", file=sys.stderr)
        sys.exit(1)
        
    vault_path = target_path.resolve()
    
    mirror_mode = is_mirror_mode() if len(sys.argv) <= 1 else False
    core_path = get_core_path()
    
    if mirror_mode:
        target_name = vault_path.name
        mirror_root = (core_path / "targets_mirror" / target_name).resolve()
        mirror_root.mkdir(parents=True, exist_ok=True)
        output_file = mirror_root / "project_tree.md"
    else:
        output_file = vault_path / "project_tree.md"
        
    today = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    
    print()
    print("=== generate_tree.py ===")
    print(f"Target Path: {vault_path}")
    if mirror_mode:
        print(f"Mode: OBSERVER (Tree in {output_file})")
    else:
        print("Mode: NATIVE")
    print()
    
    # Generate tree lines
    tree_lines = generate_tree(vault_path)
    
    root_name = vault_path.name + "/"
    
    # Markdown Header
    header = f"""---
title: "project_tree.md"
description: "Visual structure of the project. Auto-generated — do not edit manually."
type: "index"
updated: "{today}"
---

# Project Tree

> Auto-generated by `generate_tree.py`. Do not edit manually.
"""
    if mirror_mode:
        header += "> **GHOST MIRROR:** Represents the external project tree.\\n"
        
    header += f"""> Regenerate after adding, moving, or deleting folders or files.

```text
{root_name}
"""
    
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(header)
            for line in tree_lines:
                f.write(line + "\\n")
            f.write("```\\n")
            
        print(f"File generated: {output_file}")
        print()
    except Exception as e:
        print(f"Error writing file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
